language: php

php:
  - '7.3'

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - cp .env.testing .env
  - mysql -e 'CREATE DATABASE testing;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate:install --env=testing --no-interaction
  - php artisan doctrine:generate:proxies

script:
  - vendor/bin/phpunit
